# Generated by Django 5.1.4 on 2024-12-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatgroup_users_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
    ]
